============================================================
测试不同的 API 端点和请求格式
============================================================


### 测试用例 1 - 服务器 http://localhost:40005 ###

测试: http://localhost:40005/generate
------------------------------------------------------------
错误: HTTPConnectionPool(host='localhost', port=40005): Max retries exceeded with url: /generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e205eb30>: Failed to establish a new connection: [Errno 111] Connection refused'))


### 测试用例 2 - 服务器 http://localhost:40005 ###

测试: http://localhost:40005/generate
------------------------------------------------------------
错误: HTTPConnectionPool(host='localhost', port=40005): Max retries exceeded with url: /generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e205f430>: Failed to establish a new connection: [Errno 111] Connection refused'))


### 测试用例 3 - 服务器 http://localhost:40005 ###

测试: http://localhost:40005/v1/completions
------------------------------------------------------------
错误: HTTPConnectionPool(host='localhost', port=40005): Max retries exceeded with url: /v1/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e205fdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))


### 测试用例 4 - 服务器 http://localhost:40005 ###

测试: http://localhost:40005/generate
------------------------------------------------------------
错误: HTTPConnectionPool(host='localhost', port=40005): Max retries exceeded with url: /generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e205ef80>: Failed to establish a new connection: [Errno 111] Connection refused'))


### 测试用例 1 - 服务器 http://localhost:40006 ###

测试: http://localhost:40006/generate
------------------------------------------------------------
错误: HTTPConnectionPool(host='localhost', port=40006): Max retries exceeded with url: /generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e205e2c0>: Failed to establish a new connection: [Errno 111] Connection refused'))


### 测试用例 2 - 服务器 http://localhost:40006 ###

测试: http://localhost:40006/generate
------------------------------------------------------------
错误: HTTPConnectionPool(host='localhost', port=40006): Max retries exceeded with url: /generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e1ebc6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))


### 测试用例 3 - 服务器 http://localhost:40006 ###

测试: http://localhost:40006/v1/completions
------------------------------------------------------------
错误: HTTPConnectionPool(host='localhost', port=40006): Max retries exceeded with url: /v1/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e1ebcf70>: Failed to establish a new connection: [Errno 111] Connection refused'))


### 测试用例 4 - 服务器 http://localhost:40006 ###

测试: http://localhost:40006/generate
------------------------------------------------------------
错误: HTTPConnectionPool(host='localhost', port=40006): Max retries exceeded with url: /generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e205edd0>: Failed to establish a new connection: [Errno 111] Connection refused'))


### 测试路由器 ###

测试: http://localhost:40009/generate
------------------------------------------------------------
错误: HTTPConnectionPool(host='localhost', port=40009): Max retries exceeded with url: /generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84e205f3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
